- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy nginx config
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: 0644

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

